name: mtaa_frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  airplane_mode_checker: ^3.1.0
  app_settings: ^5.2.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dart_jsonwebtoken: ^3.2.0
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.10
  form_field_validator: ^1.1.0
  get_it: ^8.0.3
  go_router: ^14.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  localstore: ^1.4.0
  open_settings_plus: ^0.4.0
  path: ^1.9.0
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.29+1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.24.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1

flutter:
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
  assets:
    - assets/svgs/
    - assets/images/
    - assets/icons/
  uses-material-design: true